<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>ApiDocs.Mcp</AssemblyName>
    <RootNamespace>ApiDocs.Mcp</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ApiDocs.Application\ApiDocs.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ModelContextProtocol" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="ApiDocs.Mcp.Stdio" />
    <InternalsVisibleTo Include="ApiDocs.Mcp.Http" />
    <InternalsVisibleTo Include="ApiDocs.Tests" />
  </ItemGroup>

</Project>
